version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: mem
      QUERY_PORT: 9411
    networks:
      - notification-net

networks:
  notification-net:
    driver: bridge
